### PR TITLE
Android XML completion

### PR DESCRIPTION
**Pull request by dhleong**
This PR adds some semi-competent completion for Android XML files via the ADT plugin. It is unfortunately hacky, relying on some reflection and some copying of code from ADT source, etc. (though the latter is mostly to avoid using private methods via reflection, which seems more likely to break in an update than the others. 

If you have any thoughts on reducing coupling (IE: to prevent everything from exploding if Google releases a new ADT that breaks all the things), or really any ideas for improvement, I'm definitely open to suggestions. I tried to follow existing work for JDT and pydev and CDT as guidelines for what you might find acceptable. 

Known issue: Though most attributes seem to be suggested as expected, it refuses to propose `android:layout_width` and friends, as well as their values. I'm at a loss as to why; I've waded through a lot of ADT code, but I'm not super familiar with the completion APIs, so perhaps there's some crucial binding-to-the-project bit that I'm missing. The weirdest part is that the `LayoutContentAssist` class doesn't seem to even be attempting to propose these things—it only seems to want to propose the element names and FQNs for EG the `<view class="**">` things. I compensated a little bit by mixing in some hacks around the `ValuesContentAssist`, but of course those aren't filtered by which apply to the current View, so it's less than ideal....

### CODE REVIEW

**Comment by gopar** [comment]
@dhleong Any updates on this? It would be pretty awesome to get xml completion \o/

**Comment by dhleong** [comment]
@gopar Unfortunately I stopped using eclipse when it became clear that Google had no interest in continuing to improve support for it. The lack of proper Gradle support really became a deal-breaker—my primary project at the time just had too many dependencies to reasonably manage the old fashioned way.

I believe the state of this ticket was that it generally works, but @ervandew had wanted the Vim completion function merged into the core version; I described my difficulty doing so and proposed a solution, but didn't get any feedback. I can't see myself working on this further, but you're welcome to pick up where I left off....

**Comment by ervandew** [comment]
I admittedly put this one low on my list when I saw that google decided to stop developing the eclipse plugin. I'm not sure what eclim's future android support will look like, but at some point it won't have the benefit of relying on the adt, so I'm reluctant to add features that could break unexpectedly or will have to be removed in the near future.

**Comment by ervandew** [comment]
Closing this out since I ended up removing android support from eclim.

**Pull request closed without merging**
