### PR TITLE
Fix bug where Java autocomplete that required an import would delete the line.

### PR DESCRIPTION
**Pull request by senbrow**
(see the comment I left on the commit)

### CODE REVIEW

**Comment by ervandew** [comment]
I wonder if this is a YCM specific issue since I can't reproduce it. Can you see if you still have the problem with YCM disabled?

**Comment by ervandew** [comment]
When I remove the `\<c-e>` I get a temporary "No completions found" message, which isn't ideal. 
Instead of removing the `\<c-e>` can you try switching that to `\<c-y>` instead? That may resolve the problem.

**Comment by senbrow** [comment]
Yep, switching `\<c-e>` for `\<c-y>` seemed to do the trick!

**Comment by senbrow** [comment]
I'm not so sure \<c-y> completely resolved all problems. 😞 

Maybe this is an unrelated bug but I've noticed that now somewhat rarely as I'm typing in an autocompleted area I'll get small snippets of the available list items inserted, but mixed with my autocomplete-seed, i.e. it's not what I was actually typing nor is it an item in the list.

I'll see if I can make it more reproduceable so I can get a screen capture.

**Pull request closed without merging**
